services:
  - type: web
    name: rp-backend
    env: python
    region: singapore   # best for Sri Lanka
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    plan: free
    autoDeploy: true
